### ISSUE TITLE
Download link doesnt work 

### ISSUE THREAD

**Issue by doubled1096** [compomics/denovogui#25]
Hi,
Recently when running de novo gui (or peptide shaker and search gui) application doesnt ask to upgrade the software.  In addition when trying to download the executables the  the site http://genesis.ugent.be/maven2/com/compomics/denovogui/DeNovoGUI/1.10.1/DeNovoGUI-1.10.1-windows.zip tmes out.
Thanks,
DD

**Comment by mvaudel** [comment]
Hi DD,

Thank you for your message. Since last Friday all our system for code
management, version deployment, and websites edition is down. Despite our
everyday efforts and a most up to date system we could not prevent this
down time due to exceptional circumstances. We are actively working on
bringing the system back up again and making it more robust. More updates
will come concerning the reason of this shutdown of our services later this
week once we have confidently identified the source of the problem and
taken the necessary measures to avoid further issues.

All our apologies for the inconvenience, I will keep you posted.

Marc



2016-03-22 13:42 GMT+01:00 doubled1096 <notifications@github.com>:

**Comment by doubled1096** [comment]
Hi Marc,
Sorry to hear about the issues.  I know firsthand how frustrating these can be. Good luck.
Thanks,
DD
________________________________

**Comment by hbarsnes** [comment]
Hi DD, 

The download links should now work as before. Please let us know if you still experience any problems.

Best regards,
Harald

**Comment by doubled1096** [comment]
Thanks
